routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/

use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\CollectionController;
use App\Http\Controllers\Dashboard\LoginController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\PromoController;
use App\Http\Controllers\Dashboard\SettingsController;
use App\Http\Controllers\Dashboard\ShippingOptionController;
use App\Http\Controllers\Dashboard\SpaController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('users', 'admin.users.items')->name('users.index');
    // Route::view('users/create', 'admin.users.create')->name('users.create');
    // Route::view('users/edit', 'admin.users.edit')->name('users.edit');

    // Authentication
    Route::controller(LoginController::class)->group(function () {
        Route::get('/', 'showLoginForm')->name('admin.login');
        Route::post('/', 'login')->name('admin.login.make');
        Route::post('logout', 'logout')->name('admin.logout');
    });

    Route::middleware('auth')->group(function () {
        Route::middleware('role:super_admin')->group(function () {
            // Monitor
            Route::resource('monitor', ActivityController::class)
                ->parameters(['monitor' => 'activity'])
                ->names('monitor')
                ->only(['index', 'show']);
        });

        // Users
        Route::resource('users', UserController::class)->except(['show']);

        // Promos
        Route::resource('promos', PromoController::class)->except(['show']);

        // Collections
        Route::resource('collections', CollectionController::class)->except(['show']);

        // Shipping Options
        Route::resource('shippings', ShippingOptionController::class)
            ->parameters(['shippings' => 'shippingOption'])
            ->names('shippingOptions')
            ->except(['show']);

        // Discounts
        Route::view('discounts', 'admin.discounts.items')->name('discounts.index');
        Route::view('discounts/create', 'admin.discounts.create')->name('discounts.create');
        Route::view('discounts/edit', 'admin.discounts.edit')->name('discounts.edit');

        Route::view('website', 'admin.website.items')->name('website.index');
        Route::view('website/home', 'admin.website.home')->name('website.home');

        // Need role --> super_admin|admin
        Route::middleware('role:super_admin,admin')->group(function () {
            // Settings
            Route::controller(SettingsController::class)->group(function () {
                Route::get('settings', 'index')->name('settings.index');
                Route::put('settings/{setting}', 'update')->name('settings.update');
                Route::get('settings/{shippingSetting}/free-shipping', 'shipping')->name('settings.shipping');
            });
        });

        // Orders
        Route::resource('orders', OrderController::class)->only(['index', 'edit', 'update', 'destroy']);

        Route::controller(SpaController::class)
            ->prefix('spa')->group(function () {
                Route::get('products', 'products')->name('spa.products');
            });

        // Blog
        Route::resource('blog', PostController::class)
            ->parameters(['blog' => 'post'])
            ->names('posts')
            ->except('show');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Site Routes
|--------------------------------------------------------------------------
|
*/

use App\Http\Controllers\CustomerSessionController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::name('site.')->group(function () {
    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('/', 'home')->name('home');

    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('localization/{locale}', [LocalizationController::class, 'index'])->name('localization');
    Route::get('blog', [SiteController::class, 'blog'])->name('blog');
    Route::get('blog/{post:slug}', [SiteController::class, 'post'])->name('post');
});

Route::name('shop.')->group(function () {
    // eShop Routes

    Route::get('shop/{collection:slug?}', [SiteController::class, 'shop'])->name('index');
    Route::get('shop/{collection:slug}/{product:slug}/{any?}', [SiteController::class, 'productOfCollection'])->name('product.of.collection')->where('any', '.*');
    Route::get('shop/category/{category:slug}/{product}/{any?}', [SiteController::class, 'productOfCategory'])->name('product.of.category')->where('any', '.*');
    Route::view('cart', 'shop.cart')->name('cart');
    Route::view('checkout', 'shop.checkout')->name('checkout');
    Route::match(['get', 'post'], 'checkout/confirmation', [PaymentController::class, 'pay'])->name('process');
    Route::get('checkout/order/{order}', [PaymentController::class, 'order'])->name('order');

    Route::middleware('auth.at:shop')->group(function () {
        Route::get('account', [CustomerSessionController::class, 'account'])->name('account');
    });
});

/*
|--------------------------------------------------------------------------
| Vue routing support
|--------------------------------------------------------------------------
|
*/

// Route::any('/{any}', 'SiteController@index')->where('any', '.*');

app/Models/Collection.php
<?php

namespace App\Models;

use App\Asteroide\Traits\FileUrls;
use App\Asteroide\Traits\SlugRouting;
use App\Models\Accessors\CollectionAccessors;
use Illuminate\Database\Eloquent\Model;

class Collection extends Model
{
    use FileUrls,
        SlugRouting,
        CollectionAccessors;

    protected $fillable = [
        'title',
        'description',
        'cover_image_path',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];

    protected $appends = [
        'cover',
        // 'link',
    ];

    /**
     * Get all of the products for the collection
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function products()
    {
        return $this->morphMany(Product::class, 'productable');
    }

    public function productsThroughCategories()
    {
        return $this->hasManyThrough(Product::class, Category::class, 'categorizable_id', 'productable_id')->where('productable_type', 'App\Models\Category');
    }

    /**
     * Get all of the blocks for the collection
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function blocks()
    {
        return $this->morphMany(Block::class, 'blockable');
    }

    /**
     * Get all of the categories for the collection
     *
     * @return \Illuminate\Database\Eloquent\Relations\MorphMany
     */
    public function categories()
    {
        return $this->morphMany(Category::class, 'categorizable');
    }

    public function hasCategories()
    {
        return $this->categories->count() > 0;
    }
}

app/Http/Controllers/Dashboard/CollectionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Asteroide\Facades\Monitor;
use App\Asteroide\Traits\ControllerHelpers;
use App\Asteroide\Traits\DealWithFiles;
use App\Asteroide\Traits\Notifications;
use App\Http\Controllers\Controller;
use App\Http\Requests\CollectionRequest;
use App\Models\Collection;

class CollectionController extends Controller
{
    use ControllerHelpers,
        Notifications,
        DealWithFiles;

    public function __construct()
    {
        $this->addNotifications([
            'index' => 'Collection created successfully',
            'update' => 'Your changes have been saved',
            'destroy' => 'A collections has been deleted',
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $collections = Collection::paginate($this->itemsPerPage);

        return view('admin.collections.items', compact('collections'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $collections = Collection::paginate($this->itemsPerPage);

        return view('admin.collections.create', compact('collections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\CollectionRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CollectionRequest $request)
    {
        $collection = Collection::create($request->all());

        if ($request->hasFile('cover')) {
            $collection->cover_image_path = $this->saveFile("collections/{$collection->id}", $request->cover);
        }

        Monitor::audit(fn () => $collection->save())->addDescription('New collection created');

        $this->prepareNotification($request);

        return redirect()->route('collections.edit', compact('collection'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function edit(Collection $collection)
    {
        $collections = Collection::paginate($this->itemsPerPage);

        return view('admin.collections.edit', compact('collections', 'collection'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\CollectionRequest  $request
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function update(CollectionRequest $request, Collection $collection)
    {
        $collection->fill($request->all());

        if ($request->hasFile('cover')) {
            $this->deleteFile($collection->cover_image_path);
            $collection->cover_image_path = $this->saveFile("collections/{$collection->id}", $request->cover);
        }

        Monitor::model($collection)
            ->audit(fn () => $collection->save())
            ->addDescription('Collection updated');

        $this->prepareNotification($request);

        return redirect()->route('collections.edit', compact('collection'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Collection  $collection
     * @return \Illuminate\Http\Response
     */
    public function destroy(Collection $collection)
    {
        $this->deleteDir("collections/{$collection->id}");

        Monitor::model($collection)
            ->audit(fn () => $collection->delete())
            ->addDescription('Collection modified');

        $this->prepareNotification(request());

        return redirect()->route('collections.index');
    }
}

resources/views/admin/collections/create.blade.php
@extends('admin.collections.items')

{{-- Seccion de Form --}}
@section('form')

<div class="formularios white" id="collection_form">

    <form action="{{ route('collections.store') }}" method="POST" enctype="multipart/form-data" ref="createForm">
        @csrf

        <div class="fotos" id="collection_cover">
            <div class="foto">
                <input type="file" name="cover" @change="setImage" accept="image/*">
                <div class="type">
                    <i class="fa fa-image" aria-hidden="true"></i>
                    <label>Collection Cover</label>
                </div>
            </div>
        </div>

        <div class="input">
            <label>Collection</label>
            <input type="text" name="title" value="{{ old('title') }}" placeholder="Collection">
            <div class="focus"></div>
        </div>

        <div class="input">
            <label>Description</label>
            <textarea name="description" placeholder="Description" rows="8">{{ old('description') }}</textarea>
            <div class="focus"></div>
        </div>

        <button type="button" @click="saveWithSpinner($refs.createForm)">Done</button>

    </form>


</div>

<panel-change-view view="edit_view"></panel-change-view>

<panel-config :actions="['hideActions', 'hidePreview']"></panel-config>

@endsection
{{-- Seccion de Form --}}

resources/views/admin/collections/edit.blade.php
@extends('admin.collections.items')


{{-- Seccion View --}}

@section('preview')

<div id="collection_preview">

</div>

@endsection

{{-- Seccion View --}}





{{-- Seccion de Form --}}

@section('form')

<div class="formularios" id="collection_form">



    <div class="seccion">
        <h6>{{ $collection->title }}</h6>
        <div class="content">

            <div v-if="editing">

                <form action="{{ route('collections.update', compact('collection')) }}" method="POST" enctype="multipart/form-data" ref="updateForm">
                    @csrf
                    @method('PUT')

                    <div class="fotos" id="collection_cover">
                        <div class="foto" :style="imgBackground('{{ $collection->cover }}')">
                            <input type="file" name="cover" @change="setImage" accept="image/*">
                            <div class="type">
                                <i class="fa fa-image" aria-hidden="true"></i>
                                <label>Collection Cover</label>
                            </div>
                        </div>
                    </div>

                    <div class="input">
                        <label>Collection</label>
                        <input type="text" name="title" value="{{ old('title', $collection->title) }}" placeholder="Collection">
                        <div class="focus"></div>
                    </div>

                    <div class="input">
                        <label>Description</label>
                        <textarea name="description" placeholder="Description" rows="8">{{ old('description', $collection->description) }}</textarea>
                        <div class="focus"></div>
                    </div>

                    <button type="button" @click="saveWithSpinner($refs.updateForm)">Done</button>

                </form>

            </div>

            <button type="button" v-if="!editing" @click="editing = true">Edit collection info</button>

            <form id="delete_lines_form" action="{{ route('collections.destroy', compact('collection')) }}" method="post">
                @csrf
                @method('DELETE')
            </form>

        </div>



    </div>

    <div class="seccion" id="categories">
        <h6>Categories</h6>
        <div class="content">

            <blocks-categories :routes="{{ json_encode([
					'index' => route('categories.index', ['type' => 'collection', 'model' => $collection]),
				]) }}"
				:collection-id="{{ $collection->id }}">
            </blocks-categories>

        </div>
    </div>


</div>

<panel-change-view view="edit_view"></panel-change-view>

<panel-config :actions="['hidePreview']"></panel-config>

<panel-delete-item message="Delete this collection? ({{ $collection->title }})" delete-route="{{ route('collections.destroy', compact('collection')) }}"></panel-delete-item>

<panel-live-view-item live-route="{{ route('shop.index', compact('collection')) }}"></panel-live-view-item>

@endsection
{{-- Seccion de Form --}}

resources/views/admin/collections/items.blade.php
@extends('admin.dashboard')

@section('title', 'Admin | Collections')

@section('bar_title', 'Collections')

{{-- Seccion de items --}}
@section('items')

<a href="{{ route('collections.create') }}">
    <div class="item collection_item new">
        <label>Add collection</label>
    </div>
</a>


@foreach ($collections as $collection)
<a href="{{ route('collections.edit', compact('collection')) }}">
    <div class="item collection_item">

        <div class="foto" :style="imgBackground('{{ $collection->cover }}')"></div>

        <div class="texto">
            <strong>{{ $collection->title }}</strong>
        </div>

    </div>
</a>
@endforeach

{{ $collections->links() }}

<panel-config :actions="['hideFilters', 'hideSearch']"></panel-config>

@endsection

{{-- Seccion de items --}}