routes/dashboard.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
|
*/

use App\Http\Controllers\Dashboard\ActivityController;
use App\Http\Controllers\Dashboard\CollectionController;
use App\Http\Controllers\Dashboard\LoginController;
use App\Http\Controllers\Dashboard\OrderController;
use App\Http\Controllers\Dashboard\PostController;
use App\Http\Controllers\Dashboard\PromoController;
use App\Http\Controllers\Dashboard\SettingsController;
use App\Http\Controllers\Dashboard\ShippingOptionController;
use App\Http\Controllers\Dashboard\SpaController;
use App\Http\Controllers\Dashboard\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin')->group(function () {
    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('users', 'admin.users.items')->name('users.index');
    // Route::view('users/create', 'admin.users.create')->name('users.create');
    // Route::view('users/edit', 'admin.users.edit')->name('users.edit');

    // Authentication
    Route::controller(LoginController::class)->group(function () {
        Route::get('/', 'showLoginForm')->name('admin.login');
        Route::post('/', 'login')->name('admin.login.make');
        Route::post('logout', 'logout')->name('admin.logout');
    });

    Route::middleware('auth')->group(function () {
        Route::middleware('role:super_admin')->group(function () {
            // Monitor
            Route::resource('monitor', ActivityController::class)
                ->parameters(['monitor' => 'activity'])
                ->names('monitor')
                ->only(['index', 'show']);
        });

        // Users
        Route::resource('users', UserController::class)->except(['show']);

        // Promos
        Route::resource('promos', PromoController::class)->except(['show']);

        // Collections
        Route::resource('collections', CollectionController::class)->except(['show']);

        // Shipping Options
        Route::resource('shippings', ShippingOptionController::class)
            ->parameters(['shippings' => 'shippingOption'])
            ->names('shippingOptions')
            ->except(['show']);

        // Discounts
        Route::view('discounts', 'admin.discounts.items')->name('discounts.index');
        Route::view('discounts/create', 'admin.discounts.create')->name('discounts.create');
        Route::view('discounts/edit', 'admin.discounts.edit')->name('discounts.edit');

        Route::view('website', 'admin.website.items')->name('website.index');
        Route::view('website/home', 'admin.website.home')->name('website.home');

        // Need role --> super_admin|admin
        Route::middleware('role:super_admin,admin')->group(function () {
            // Settings
            Route::controller(SettingsController::class)->group(function () {
                Route::get('settings', 'index')->name('settings.index');
                Route::put('settings/{setting}', 'update')->name('settings.update');
                Route::get('settings/{shippingSetting}/free-shipping', 'shipping')->name('settings.shipping');
            });
        });

        // Orders
        Route::resource('orders', OrderController::class)->only(['index', 'edit', 'update', 'destroy']);

        Route::controller(SpaController::class)
            ->prefix('spa')->group(function () {
                Route::get('products', 'products')->name('spa.products');
            });

        // Blog
        Route::resource('blog', PostController::class)
            ->parameters(['blog' => 'post'])
            ->names('posts')
            ->except('show');
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Site Routes
|--------------------------------------------------------------------------
|
*/

use App\Http\Controllers\CustomerSessionController;
use App\Http\Controllers\LocalizationController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;

Route::name('site.')->group(function () {
    // Nueva syntaxis ---> Route::get('user/profile', [UserProfileController::class, 'show'])->name('profile');

    // RUTAS SIMPLES PARA VIEWS EJEMPLO
    // Route::view('/', 'home')->name('home');

    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('localization/{locale}', [LocalizationController::class, 'index'])->name('localization');
    Route::get('blog', [SiteController::class, 'blog'])->name('blog');
    Route::get('blog/{post:slug}', [SiteController::class, 'post'])->name('post');
});

Route::name('shop.')->group(function () {
    // eShop Routes

    Route::get('shop/{collection:slug?}', [SiteController::class, 'shop'])->name('index');
    Route::get('shop/{collection:slug}/{product:slug}/{any?}', [SiteController::class, 'productOfCollection'])->name('product.of.collection')->where('any', '.*');
    Route::get('shop/category/{category:slug}/{product}/{any?}', [SiteController::class, 'productOfCategory'])->name('product.of.category')->where('any', '.*');
    Route::view('cart', 'shop.cart')->name('cart');
    Route::view('checkout', 'shop.checkout')->name('checkout');
    Route::match(['get', 'post'], 'checkout/confirmation', [PaymentController::class, 'pay'])->name('process');
    Route::get('checkout/order/{order}', [PaymentController::class, 'order'])->name('order');

    Route::middleware('auth.at:shop')->group(function () {
        Route::get('account', [CustomerSessionController::class, 'account'])->name('account');
    });
});

/*
|--------------------------------------------------------------------------
| Vue routing support
|--------------------------------------------------------------------------
|
*/

// Route::any('/{any}', 'SiteController@index')->where('any', '.*');

app/Models/Order.php
<?php

namespace App\Models;

use App\Models\Accessors\OrderAccessors;
use Illuminate\Database\Eloquent\Model;
use Laravel\Scout\Searchable;

class Order extends Model
{
    use Searchable,
        OrderAccessors;

    /**
     * status -> [created, waiting_paypal, waiting_oxxo, error_paypal, error_card, error_oxxo, expired_oxxo, paid,  complete]
     * payment_method -> [card, paypal, oxxo_cash]
     *
     * @var array
     */
    protected $fillable = [
        'reference',
        'status',
        'payment_method',
        'payment_reference',
        'payment_holders_name',
        'card_brand',
        'card_last4',
        'receipt_url',
        'error_message',
        'approval_link',
        'paid_at',
        'currency_code',
        'amount',
        'shipping_fee',
        'subtotal',
        'discount',
        'track_number',
        'expires_at',
        'carrier_name',
        'tracking_link',
    ];

    protected $dates = [
        'paid_at',
        'created_at',
        'updated_at',
        'expires_at',
    ];

    // protected $with = [
    // 	'customer'
    // ];

    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function shippingOption()
    {
        return $this->belongsTo(ShippingOption::class);
    }

    public function products()
    {
        return $this->belongsToMany(Product::class)
            ->using(OrderProduct::class)
            ->withPivot([
                'quantity',
                'charged_price',
                'product_at_moment',
                'variant_at_moment',
            ])->withTimestamps();
    }

    /**
     * Get the indexable data array for the model.
     *
     * @return array
     */
    public function toSearchableArray()
    {
        return $this->toArray() + [
            // 'customer' => $this->customer
        ];
    }

    public function paidWithCard()
    {
        return $this->payment_method === 'card';
    }

    public function paidWithPayPal()
    {
        return $this->payment_method === 'paypal';
    }

    public function paidWithOxxo()
    {
        return $this->payment_method === 'oxxo_cash';
    }

    public function hasPaymentError()
    {
        return $this->status === 'error_paypal' || $this->status === 'error_card';
    }
}

app/Http/Controllers/Dashboard/OrderController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Asteroide\Traits\ControllerHelpers;
use App\Asteroide\Traits\Notifications;
use App\Http\Controllers\Controller;
use App\Mail\OrderShipped;
use App\Models\Carrier;
use App\Models\Order;
use App\Models\ShippingOption;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class OrderController extends Controller
{
    use ControllerHelpers,
        Notifications;

    public function __construct()
    {
        $this->addNotifications([
            'update' => 'This order has been updated',
        ]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = (filled($q = request()->query('q')) ? Order::search($q) : Order::with('customer')
            ->where('status', '<>', 'created'))
            ->orderBy('created_at', 'desc')->paginate($this->itemsPerPage);

        $orders->load('customer');

        return view('admin.orders.items', compact('orders'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('admin.orders.edit', [
            'orders' => Order::with('customer')->where('status', '<>', 'created')->orderBy('created_at', 'desc')->paginate($this->itemsPerPage),
            'order' => $order,
            'carriers' => Carrier::all(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        $sendShippingMail = $order->status != 'complete' && $request->status == 'complete';

        $order->fill($request->all());

        if ($request->has('shipping_option')) {
            $order->shippingOption()->associate(ShippingOption::find($request->shipping_option));
        }

        if ($sendShippingMail) {
            Mail::to($order->customer->email)->send(new OrderShipped($order));
        }

        $order->save();

        $this->prepareNotification($request);

        return redirect()->route('orders.edit', compact('order'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Order  $order
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        $order->delete();

        $this->prepareNotification(request());

        return redirect()->route('orders.index');
    }
}

resources/views/admin/orders/edit.blade.php
@extends('admin.orders.items')


{{-- Seccion View --}}

@section('preview')

<div id="order_preview">



    <div class="seccion" id="products">
        <h6>Products</h6>
        <div class="content">

            <div id="productos">

                @foreach ($order->products as $product)

                <div class="producto">
                    <div class="foto" :style="imgBackground('{{ $product->pivot->variant('cover') ?? $product->cover }}')">
                    </div>
                    <div class="cantidad">
                        <span>x{{ $product->pivot->quantity }}</span>
                    </div>
                    <div class="nombre">
                        <span>
                            {{ $product->title }}{{ $product->pivot->hasVariant() ? ' - '.$product->pivot->variant('title') : '' }}
                            {{ $product->pivot->tagsAsString() }}
                        </span>
                        <p>{{ $product->pivot->notes }}</p>

                    </div>
                    <div class="precio">
                        <b>@money($product->pivot->charged_price)</b>
                    </div>
                </div>


                @endforeach


            </div>

            <div class="content">

                <div class="contenido">

                    <div class="info">
                        <label>Subtotal</label>
                        <p>@money($order->subtotal)</p>
                    </div>

                    <div class="info">
                        <label>Shipping</label>
                        <p>@money($order->shipping_fee)</p>
                    </div>

                    @if ($order->discount > 0)
                    <div class="info">
                        <label>Discount</label>
                        <p>-@money($order->discount)</p>
                    </div>
                    @endif

                    <div class="info">
                        <label>Total</label>
                        <p>@money($order->amount)</p>
                    </div>

                </div>

            </div>

        </div>
    </div>


    <div class="seccion" id="customer">
        <h6>Customer contact information</h6>
        <div class="content">

            <div class="contenido">
                <div class="info">
                    <label>Full Name</label>
                    <p>{{ $order->customer->full_name }}</p>
                </div>
                <div class="info">
                    <label>Email</label>
                    <p>{{ $order->customer->email }}</p>
                </div>
                <div class="info">
                    <label>Phone number</label>
                    <p>{{ $order->customer->phone }}</p>
                </div>
            </div>
        </div>

    </div>

    <div class="seccion" id="shipping">
        <h6>Shipping information</h6>
        <div class="content">

            <div class="contenido">

                <div class="info">
                    <label>Street Address</label>
                    <p>{{ $order->customer->address }}</p>
                </div>
                <div class="info">
                    <label>City</label>
                    <p>{{ $order->customer->city }}</p>
                </div>
                <div class="info">
                    <label>Country</label>
                    <p>{{ $order->customer->country }}</p>
                </div>
                <div class="info">
                    <label>Postal Code</label>
                    <p>{{ $order->customer->postal_code }}</p>
                </div>
                <div class="info">
                    <label>Fee</label>
                    <p>@money($order->shipping_fee)</p>
                </div>

                @if (filled($order->customer->references))
                <div class="info">
                    <label>Delivery instructions</label>
                    <p>{{ $order->customer->references }}</p>
                </div>
                @endif


                @if (filled($order->track_number))
                <div class="info">
                    <label>Carrier</label>
                    <p>{{ $order->shippingOption->name }}</p>
                </div>

                <div class="info">
                    <label>Tracking number</label>
                    <p>{{ $order->track_number }}</p>
                </div>
                @endif


            </div>

        </div>
    </div>

    <div class="seccion" id="payment">
        <h6>{{ $order->hasPaymentError() ? $order->payment_error_message : 'Payment' }}</h6>
        <div class="content">

            <div class="contenido">
                <div class="info">
                    <label>Method</label>
                    <p>{{ $order->paidWithCard() ? 'Credit/Debit Card' : 'PayPal' }}</p>
                </div>

                @if ($order->paidWithCard() && !$order->hasPaymentError())

                <div class="info">
                    <label>Cardholder's name</label>
                    <p>{{ $order->payment_holders_name }}</p>
                </div>
                <div class="info">
                    <label>Card</label>
                    <p>{{ $order->card_brand }} - {{ $order->card_last4 }}</p>
                </div>

                @endif

                @if ($order->paidWithPayPal() && !$order->hasPaymentError())

                <div class="info">
                    <label>Paypal account</label>
                    <p>{{ $order->payment_holders_name }}</p>
                </div>

                @endif

                @if($order->hasPaymentError())
                <div class="info">
                    <label>Issue</label>
                    <p>{{ $order->error_message }}</p>
                </div>
                @else
                <div class="info">
                    <label>Reference</label>
                    <p>{{ $order->payment_reference }}</p>
                </div>
                @endif

                <div class="info">
                    <label>{{ $order->hasPaymentError() ? 'Pending amount' : 'Amount' }}</label>
                    <p>@money($order->amount)</p>
                </div>

                @if (filled($order->receipt_url) && !$order->hasPaymentError())
                <div class="info">
                    <label>Receipt link</label>
                    <p>
                        <a href="{{ $order->receipt_url }}" target="_tab">
                            <u style="text-decoration: underline;">Stripe Receipt</u>
                        </a>
                    </p>
                </div>
                @endif
            </div>

        </div>
    </div>


</div>

@endsection

{{-- Seccion View --}}





{{-- Seccion de Form --}}

@section('form')

<div class="formularios" id="order_form">


    <div class="seccion">
        <h6>Order ID: <b>#{{ $order->reference }}</b></h6>
        <div class="content">

            <form action="{{ route('orders.update', compact('order')) }}" method="POST" enctype="multipart/form-data" ref="updateForm">
                @csrf
                @method('PUT')

                <!-- add class: paid, complete o error -->
                <div class="input {{ $order->hasPaymentError() ? 'error' : $order->status }}" id="status">
                    <label>Status</label>
                    <input type="text" value="{{ $order->payment_error_message }}" placeholder="Status">
                    <div class="focus"></div>
                </div>

                <div class="input">
                    <label class="stay">Change to</label>
                    <select name="status">
                        <option selected disabled>Choose a status</option>
                        <option value="complete">Complete</option>
                        <option value="paid">Paid</option>
                    </select>
                    <div class="focus"></div>
                </div>

                <div class="input">
                    <label>Chossen option</label>
                    <input type="text" value="{{ $order->shippingOption->name. '/'. $order->shippingOption->description }} - @money($order->shippingOption->fee)" placeholder="Shipping option" readonly>
                    <div class="focus"></div>
                </div>

                <div class="input">
                    <label>Tracking ID</label>
                    <input type="text" name="track_number" value="{{ old('track_number', $order->track_number) }}" placeholder="Tracking ID">
                    <div class="focus"></div>
                </div>

                <button type="button" @click="saveWithSpinner($refs.updateForm)">Done</button>

            </form>

        </div>
    </div>



    <form id="delete_orders_form" action="{{ route('orders.destroy', compact('order')) }}" method="post">
        @csrf
        @method('DELETE')
    </form>

</div>

<panel-change-view view="preview"></panel-change-view>

<panel-config :actions="['hideActionShow']"></panel-config>

<panel-delete-item message="Delete this order? (#{{ $collection->reference }})" delete-route="{{ route('orders.destroy', compact('order')) }}"></panel-delete-item>

@endsection
{{-- Seccion de Form --}}

resources/views/admin/orders/items.blade.php
@extends('admin.dashboard')

@section('title', 'Admin | Orders')

@section('bar_title', 'Orders')

@section('search_route', 'orders.index')

{{-- Seccion de items --}}
@section('items')


@foreach ($orders as $order)
<a href="{{ route('orders.edit', compact('order')) }}">
    <div class="item order_item">

        <div class="texto">
            <strong>{{ $order.customer.email }}</strong>
            <span>{{ $order->created_at->format('d/m/Y') }}</span>
        </div>

        <order-status status="{{ $order->status }}"></order-status>

    </div>
</a>
@endforeach


{{ $orders->links() }}

<panel-config :actions="['hideFilters']"></panel-config>

@endsection

{{-- Seccion de items --}}